window.NEPALI_CONTENT = {
  phaseIntervals: [0, 1, 3, 7, 16, 35],
  words: [
    { id: "namaste", nepali: "नमस्ते", roman: "namaste", german: "Hallo", category: "Begrüßung" },
    { id: "dhanyabad", nepali: "धन्यवाद", roman: "dhanyabad", german: "Danke", category: "Begrüßung" },
    { id: "kripaya", nepali: "कृपया", roman: "kripaya", german: "bitte", category: "Begrüßung" },
    { id: "maaf", nepali: "माफ गर्नुहोस्", roman: "maaf garnuhos", german: "Entschuldigung", category: "Begrüßung" },
    { id: "ho", nepali: "हो", roman: "ho", german: "ja / ist", category: "Basis" },
    { id: "hoina", nepali: "होइन", roman: "hoina", german: "nein / ist nicht", category: "Basis" },
    { id: "thik", nepali: "ठीक", roman: "thik", german: "okay / richtig", category: "Basis" },
    { id: "ramro", nepali: "राम्रो", roman: "ramro", german: "gut / schön", category: "Basis" },
    { id: "naramro", nepali: "नराम्रो", roman: "naramro", german: "schlecht", category: "Basis" },
    { id: "ma", nepali: "म", roman: "ma", german: "ich", category: "Personen" },
    { id: "tapai", nepali: "तपाईं", roman: "tapai", german: "Sie / du", category: "Personen" },
    { id: "u", nepali: "ऊ", roman: "u", german: "er / sie", category: "Personen" },
    { id: "hami", nepali: "हामी", roman: "hami", german: "wir", category: "Personen" },
    { id: "sathi", nepali: "साथी", roman: "sathi", german: "Freund / Freundin", category: "Personen" },
    { id: "parivar", nepali: "परिवार", roman: "parivar", german: "Familie", category: "Personen" },
    { id: "aama", nepali: "आमा", roman: "aama", german: "Mutter", category: "Personen" },
    { id: "buba", nepali: "बुबा", roman: "buba", german: "Vater", category: "Personen" },
    { id: "bachcha", nepali: "बच्चा", roman: "bachcha", german: "Kind", category: "Personen" },
    { id: "naam", nepali: "नाम", roman: "naam", german: "Name", category: "Vorstellen" },
    { id: "bhasa", nepali: "भाषा", roman: "bhasa", german: "Sprache", category: "Vorstellen" },
    { id: "nepali", nepali: "नेपाली", roman: "nepali", german: "Nepali / nepalesisch", category: "Vorstellen" },
    { id: "siknu", nepali: "सिक्नु", roman: "siknu", german: "lernen", category: "Vorstellen" },
    { id: "pani", nepali: "पानी", roman: "pani", german: "Wasser", category: "Essen" },
    { id: "khana", nepali: "खाना", roman: "khana", german: "Essen", category: "Essen" },
    { id: "bhat", nepali: "भात", roman: "bhat", german: "Reis", category: "Essen" },
    { id: "chiya", nepali: "चिया", roman: "chiya", german: "Tee", category: "Essen" },
    { id: "dudh", nepali: "दूध", roman: "dudh", german: "Milch", category: "Essen" },
    { id: "roti", nepali: "रोटी", roman: "roti", german: "Brot / Fladenbrot", category: "Essen" },
    { id: "falful", nepali: "फलफूल", roman: "falful", german: "Obst", category: "Essen" },
    { id: "syau", nepali: "स्याउ", roman: "syau", german: "Apfel", category: "Essen" },
    { id: "tarkari", nepali: "तरकारी", roman: "tarkari", german: "Gemüse / Curry", category: "Essen" },
    { id: "dal", nepali: "दाल", roman: "dal", german: "Linsen", category: "Essen" },
    { id: "nun", nepali: "नुन", roman: "nun", german: "Salz", category: "Essen" },
    { id: "ghar", nepali: "घर", roman: "ghar", german: "Haus", category: "Orte" },
    { id: "kotha", nepali: "कोठा", roman: "kotha", german: "Zimmer", category: "Orte" },
    { id: "school", nepali: "विद्यालय", roman: "vidyalaya", german: "Schule", category: "Orte" },
    { id: "bajar", nepali: "बजार", roman: "bajar", german: "Markt", category: "Orte" },
    { id: "pasal", nepali: "पसल", roman: "pasal", german: "Laden", category: "Orte" },
    { id: "bato", nepali: "बाटो", roman: "bato", german: "Straße / Weg", category: "Orte" },
    { id: "bus", nepali: "बस", roman: "bas", german: "Bus", category: "Reise" },
    { id: "taxi", nepali: "ट्याक्सी", roman: "tyaksi", german: "Taxi", category: "Reise" },
    { id: "hotel", nepali: "होटल", roman: "hotel", german: "Hotel", category: "Reise" },
    { id: "sauchalaya", nepali: "शौचालय", roman: "sauchalaya", german: "Toilette", category: "Reise" },
    { id: "aaja", nepali: "आज", roman: "aaja", german: "heute", category: "Zeit" },
    { id: "bholi", nepali: "भोलि", roman: "bholi", german: "morgen", category: "Zeit" },
    { id: "hijo", nepali: "हिजो", roman: "hijo", german: "gestern", category: "Zeit" },
    { id: "bihana", nepali: "बिहान", roman: "bihana", german: "Morgen / vormittags", category: "Zeit" },
    { id: "beluka", nepali: "बेलुका", roman: "beluka", german: "Abend", category: "Zeit" },
    { id: "ahile", nepali: "अहिले", roman: "ahile", german: "jetzt", category: "Zeit" },
    { id: "pachi", nepali: "पछि", roman: "pachi", german: "später / danach", category: "Zeit" },
    { id: "ek", nepali: "एक", roman: "ek", german: "eins", category: "Zahlen" },
    { id: "dui", nepali: "दुई", roman: "dui", german: "zwei", category: "Zahlen" },
    { id: "tin", nepali: "तीन", roman: "tin", german: "drei", category: "Zahlen" },
    { id: "char", nepali: "चार", roman: "char", german: "vier", category: "Zahlen" },
    { id: "panch", nepali: "पाँच", roman: "panch", german: "fünf", category: "Zahlen" },
    { id: "chha_number", nepali: "छ", roman: "chha", german: "sechs", category: "Zahlen" },
    { id: "sat", nepali: "सात", roman: "sat", german: "sieben", category: "Zahlen" },
    { id: "aath", nepali: "आठ", roman: "aath", german: "acht", category: "Zahlen" },
    { id: "nau", nepali: "नौ", roman: "nau", german: "neun", category: "Zahlen" },
    { id: "das", nepali: "दश", roman: "das", german: "zehn", category: "Zahlen" },
    { id: "thulo", nepali: "ठूलो", roman: "thulo", german: "groß", category: "Eigenschaften" },
    { id: "sano", nepali: "सानो", roman: "sano", german: "klein", category: "Eigenschaften" },
    { id: "tato", nepali: "तातो", roman: "tato", german: "heiß", category: "Eigenschaften" },
    { id: "chiso", nepali: "चिसो", roman: "chiso", german: "kalt", category: "Eigenschaften" },
    { id: "mahango", nepali: "महँगो", roman: "mahango", german: "teuer", category: "Einkaufen" },
    { id: "sasto", nepali: "सस्तो", roman: "sasto", german: "billig / günstig", category: "Einkaufen" },
    { id: "kaha", nepali: "कहाँ", roman: "kaha", german: "wo", category: "Fragen" },
    { id: "ke", nepali: "के", roman: "ke", german: "was", category: "Fragen" },
    { id: "kasto", nepali: "कस्तो", roman: "kasto", german: "wie / welche Art", category: "Fragen" },
    { id: "kati", nepali: "कति", roman: "kati", german: "wie viel", category: "Fragen" }
  ],
  sentences: [
    { id: "hello", nepali: "नमस्ते।", roman: "namaste.", german: "Hallo.", category: "Begrüßung" },
    { id: "how_are_you", nepali: "तपाईंलाई कस्तो छ?", roman: "tapai lai kasto chha?", german: "Wie geht es Ihnen?", category: "Begrüßung" },
    { id: "i_am_good", nepali: "मलाई राम्रो छ।", roman: "malai ramro chha.", german: "Mir geht es gut.", category: "Begrüßung" },
    { id: "thank_you", nepali: "धन्यवाद।", roman: "dhanyabad.", german: "Danke.", category: "Begrüßung" },
    { id: "please_slowly", nepali: "कृपया बिस्तारी बोल्नुहोस्।", roman: "kripaya bistari bolnuhos.", german: "Bitte sprechen Sie langsam.", category: "Begrüßung" },
    { id: "my_name", nepali: "मेरो नाम मार्टिन हो।", roman: "mero naam Martin ho.", german: "Mein Name ist Martin.", category: "Vorstellen" },
    { id: "i_learn_nepali", nepali: "म नेपाली सिक्दै छु।", roman: "ma nepali sikdai chhu.", german: "Ich lerne Nepali.", category: "Vorstellen" },
    { id: "little_nepali", nepali: "मलाई नेपाली अलि अलि आउँछ।", roman: "malai nepali ali ali aauchha.", german: "Ich kann ein bisschen Nepali.", category: "Vorstellen" },
    { id: "this_is_water", nepali: "यो पानी हो।", roman: "yo pani ho.", german: "Das ist Wasser.", category: "Essen" },
    { id: "want_water", nepali: "मलाई पानी चाहिन्छ।", roman: "malai pani chahinchha.", german: "Ich brauche Wasser.", category: "Essen" },
    { id: "give_tea", nepali: "कृपया चिया दिनुहोस्।", roman: "kripaya chiya dinuhos.", german: "Bitte geben Sie Tee.", category: "Essen" },
    { id: "food_good", nepali: "खाना राम्रो छ।", roman: "khana ramro chha.", german: "Das Essen ist gut.", category: "Essen" },
    { id: "i_eat_rice", nepali: "म भात खान्छु।", roman: "ma bhat khanchhu.", german: "Ich esse Reis.", category: "Essen" },
    { id: "where_toilet", nepali: "शौचालय कहाँ छ?", roman: "sauchalaya kaha chha?", german: "Wo ist die Toilette?", category: "Reise" },
    { id: "where_market", nepali: "बजार कहाँ छ?", roman: "bajar kaha chha?", german: "Wo ist der Markt?", category: "Reise" },
    { id: "need_taxi", nepali: "मलाई ट्याक्सी चाहिन्छ।", roman: "malai tyaksi chahinchha.", german: "Ich brauche ein Taxi.", category: "Reise" },
    { id: "this_hotel", nepali: "यो होटल राम्रो छ।", roman: "yo hotel ramro chha.", german: "Dieses Hotel ist gut.", category: "Reise" },
    { id: "room_big", nepali: "कोठा ठूलो छ।", roman: "kotha thulo chha.", german: "Das Zimmer ist groß.", category: "Orte" },
    { id: "house_small", nepali: "घर सानो छ।", roman: "ghar sano chha.", german: "Das Haus ist klein.", category: "Orte" },
    { id: "today_good", nepali: "आज राम्रो दिन हो।", roman: "aaja ramro din ho.", german: "Heute ist ein guter Tag.", category: "Zeit" },
    { id: "tomorrow_go", nepali: "म भोलि जान्छु।", roman: "ma bholi janchhu.", german: "Ich gehe morgen.", category: "Zeit" },
    { id: "now_here", nepali: "म अहिले यहाँ छु।", roman: "ma ahile yaha chhu.", german: "Ich bin jetzt hier.", category: "Zeit" },
    { id: "how_much", nepali: "यो कति हो?", roman: "yo kati ho?", german: "Wie viel kostet das?", category: "Einkaufen" },
    { id: "too_expensive", nepali: "यो महँगो छ।", roman: "yo mahango chha.", german: "Das ist teuer.", category: "Einkaufen" },
    { id: "cheap_good", nepali: "यो सस्तो र राम्रो छ।", roman: "yo sasto ra ramro chha.", german: "Das ist günstig und gut.", category: "Einkaufen" },
    { id: "one_tea", nepali: "एक चिया दिनुहोस्।", roman: "ek chiya dinuhos.", german: "Bitte einen Tee.", category: "Zahlen" },
    { id: "two_water", nepali: "दुई पानी दिनुहोस्।", roman: "dui pani dinuhos.", german: "Bitte zwei Wasser.", category: "Zahlen" },
    { id: "what_is_this", nepali: "यो के हो?", roman: "yo ke ho?", german: "Was ist das?", category: "Fragen" },
    { id: "where_are_you", nepali: "तपाईं कहाँ हुनुहुन्छ?", roman: "tapai kaha hunuhunchha?", german: "Wo sind Sie?", category: "Fragen" },
    { id: "friend_home", nepali: "मेरो साथी घरमा छ।", roman: "mero sathi gharma chha.", german: "Mein Freund ist zu Hause.", category: "Personen" }
  ]
};

window.NEPALI_CONTENT.words.forEach((item) => {
  item.audio = `audio/words/${item.id}.wav`;
});

window.NEPALI_CONTENT.sentences.forEach((item) => {
  item.audio = `audio/sentences/${item.id}.wav`;
});
